tosca_definitions_version: alien_dsl_2_0_0

#
# Ystia Forge
# Copyright (C) 2018 Bull S. A. S. - Bull, Rue Jean Jaures, B.P.68, 78340, Les Clayes-sous-Bois, France.
# Use of this source code is governed by Apache 2 LICENSE that can be found in the LICENSE file.
#

metadata:
  template_name: org.ystia.traefik.ansible-linux
  template_version: 2.0.0-SNAPSHOT
  template_author: Ystia

imports:
  - tosca-normative-types:1.0.0-ALIEN20
  - yorc-types:1.0.0
  - org.ystia.traefik.pub:2.0.0-SNAPSHOT

node_types:
  org.ystia.traefik.ansible-linux.nodes.Traefik:
    derived_from: org.ystia.traefik.pub.nodes.Traefik
    properties:
      download_url:
        type: string
        default: "https://github.com/containous/traefik/releases/download/v1.6.4/traefik_linux-amd64"
      install_dir:
        type: string
        default: "/usr/local/bin"
        required: true
      config_dir:
        type: string
        default: "/etc/traefik"
        required: true
      enable_dashboard:
        type: boolean
        default: true
      component_version:
        type: version
        default: 1.6.4
        required: false
    interfaces:
      Standard:
        create:
          inputs:
            INSTALL_DIR: {get_property: [SELF, install_dir]}
            DOWNLOAD_URL: {get_property: [SELF, download_url]}
            CONFIG_DIR: {get_property: [SELF, config_dir]}
          implementation: playbooks/create.yaml
        configure:
          inputs:
            CONFIG_DIR: {get_property: [SELF, config_dir]}
            ENTRYPOINT_PORT: {get_property: [SELF, entrypoint, port]}
            ENTRYPOINT_PROTOCOL: {get_property: [SELF, entrypoint, protocol]}
            ENABLE_DASHBOARD: {get_property: [SELF, enable_dashboard]}
          implementation: playbooks/configure.yaml
        start: playbooks/start.yaml
        stop: playbooks/stop.yaml
        delete: playbooks/delete.yaml

  org.ystia.traefik.ansible-linux.nodes.TraefikRoute:
    derived_from: org.ystia.traefik.pub.nodes.TraefikRoute
    requirements:
      - application:
          capability: tosca.capabilities.Endpoint
          relationship: org.ystia.traefik.ansible-linux.relationships.TraefikRoutesTo
          occurrences: [0, UNBOUNDED]
    interfaces:
      Standard:
        configure:
          inputs:
            CONFIG_DIR: {get_property: [SELF, config_dir]}
            RULES: {get_property: [SELF, rules]}
          implementation: playbooks/configure_route.yaml
      
relationship_types:
  org.ystia.traefik.ansible-linux.relationships.TraefikRoutesTo:
    derived_from: tosca.relationships.RoutesTo
    interfaces:
      Configure:
        inputs:
          CONFIG_DIR: {get_property: [SOURCE, config_dir]}
          IP_ADDRESS: {get_attribute: [TARGET, ip_address]}
        add_target:
          implementation: playbooks/add_route_target.yaml
        remove_target:
          implementation: playbooks/remove_route_target.yaml
