tosca_definitions_version: alien_dsl_2_0_0

#
# Ystia Forge
# Copyright (C) 2018 Bull S. A. S. - Bull, Rue Jean Jaures, B.P.68, 78340, Les Clayes-sous-Bois, France.
# Use of this source code is governed by Apache 2 LICENSE that can be found in the LICENSE file.
#

metadata:
  template_name: org.ystia.traefik.pub
  template_version: 2.0.0-SNAPSHOT
  template_author: Ystia

description: Public interface types for Traefik reverse proxy support.


imports:
  - tosca-normative-types:1.0.0-ALIEN20

node_types:
  org.ystia.traefik.pub.nodes.Traefik:
    derived_from: tosca.nodes.SoftwareComponent
    abstract: true
    metadata:
      icon: /icons/traefik.logo.png
    capabilities:
      entrypoint: org.ystia.traefik.pub.capabilities.EntryPoint
      cfg_fragment_host: org.ystia.traefik.pub.capabilities.ConfigFragmentHost

  org.ystia.traefik.pub.nodes.TraefikRoute:
    derived_from: tosca.nodes.LoadBalancer
    abstract: true
    properties:
      rules:
        type: string
        default: ""
        required: false
    requirements:
      - cfg_host:
          capability: org.ystia.traefik.pub.capabilities.ConfigFragmentHost
          node: org.ystia.traefik.pub.nodes.Traefik
          relationship: tosca.relationships.HostedOn

capability_types:
  org.ystia.traefik.pub.capabilities.EntryPoint:
    derived_from: tosca.capabilities.Endpoint
    properties:
      port:
        type: integer
        default: 80
        required: true
        constraints:
          - in_range: [ 1, 65535 ]
      protocol:
        type: string
        default: http
        constraints:
          - valid_values: [http, https]
  
  org.ystia.traefik.pub.capabilities.ConfigFragmentHost:
    derived_from: tosca.capabilities.Container
    